### ISSUE TITLE
I Think this should get deprecated via npm

### ISSUE THREAD

**Issue by frank-dspeed** [bitovi/grunt-testee#8]
We can add all this tasks to a simple js file in testee and call it via npm i think grunt in general is not needed any more.

**Comment by andrejewski** [comment]
`grunt-testee` was originally inside Testee, which was bad because:
- The task had no tests
- Testee needed Grunt as a peer/dev dependency, which with Grunt's decline in popularity did not make sense to users

Now the Grunt task is isolated, well tested, and optional. As a separate project we can sunset Grunt support without a breaking version in Testee.

Closing as the maintenance cost of this project is very low and there was a reasoning behind breaking it out of Testee core.
